apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: demo
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: pirindb
      app.kubernetes.io/instance: demo
