package storage

import (
	"errors"
)

var (
	ErrKeyTooLarge           = errors.New("key too large")
	ErrValueTooLarge         = errors.New("value too large")
	ErrNotEnoughSpace        = errors.New("not enough space to serialize node")
	ErrNoPagesLeft           = errors.New("no pages left")
	ErrCorruptedFreelist     = errors.New("corrupted freelist")
	ErrCorruptedBlob         = errors.New("corrupted blob")
	ErrBucketNotFound        = errors.New("bucket not found")
	ErrBucketExists          = errors.New("bucket already exists")
	ErrInvalidBucketName     = errors.New("bucket name must be between 1 and 511 bytes")
	ErrTxClosed              = errors.New("transaction closed")
	ErrWriteInRxTransaction  = errors.New("write in read transaction")
	ErrNodeNotFound          = errors.New("node not found")
	ErrBlobTooLarge          = errors.New("blob too large")
	ErrBlobRequiresStreaming = errors.New("blob is too large for in-memory Get; use WriteValueTo")
	ErrUnknownItemType       = errors.New("unknown item type")
	ErrBadDbVersion          = errors.New("invalid db version")
	ErrBadDbName             = errors.New("invalid db name")
	ErrCorruptedNode         = errors.New("corrupted b-tree node")
	ErrCorruptedMeta         = errors.New("corrupted database metadata")
	ErrDatabaseClosed        = errors.New("database closed")
	ErrDatabaseFatal         = errors.New("database requires recovery")
	ErrRecoveryRequired      = errors.New("active recovery journal must be replayed before writing")
	ErrInvalidOptions        = errors.New("invalid database options")
	ErrChecksumMismatch      = errors.New("page checksum mismatch")
	ErrIntegrityCheckFailed  = errors.New("database integrity check failed")
	ErrTransactionTooLarge   = errors.New("transaction exceeds configured memory limit")
	ErrJournalRestoreFailed  = errors.New("failed to restore previous recovery journal")
)
